### ISSUE TITLE
Should we use options={} ?

### ISSUE THREAD

**Issue by lpatiny** [mljs/rolling-ball-baseline#2]
Could we imagine default values ? Based on length of array ?

Would the 2 parameters become options ?

https://github.com/kjappelbaum/rollingBallBaseline/blob/master/src/rollingBall.js#L25-L26

**Comment by kjappelbaum** [comment]
i thought a bit about it some time ago. The default here of course also depend on how broad/spiky the peaks are. I decided to set none because also the R implementors did so. But maybe we can have some (bad) ones based on the length of the array, as you suggested. Better than nothing ...
